Task a

In [16]:
reduced_h = 1       # atomic unit
m = 1               # atomic unit
L = 1.0             # atomic unit (Bohr radii)
grid_points = 2000

Task b

In [17]:
import numpy as np

def construct_laplacian(size, delta_x):
    identity_I = np.identity(size)
    off_diagonal_values = np.ones(size - 1)
    off_diagonal_I = np.diag(off_diag_values, k=-1) + np.diag(off_diag_values, k=1)

    laplacian = 1/(delta_x**2)*(-2*identity_I + off_diagonal_I)

    return laplacian

In [22]:
print(construct_laplacian(5, 1))

[[-2.  1.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.]
 [ 0.  1. -2.  1.  0.]
 [ 0.  0.  1. -2.  1.]
 [ 0.  0.  0.  1. -2.]]


Task c

In [19]:
laplacian = construct_laplacian(5, 1)
H = -(reduced_h**2)/(2*m) * laplacian

In [23]:
eigenvalues, eigenvectors = np.linalg.eig(H)
print(eigenvalues)
print(eigenvectors)

[1.8660254 1.5       1.        0.1339746 0.5      ]
[[ 2.88675135e-01  5.00000000e-01  5.77350269e-01  2.88675135e-01
  -5.00000000e-01]
 [-5.00000000e-01 -5.00000000e-01 -4.16874298e-16  5.00000000e-01
  -5.00000000e-01]
 [ 5.77350269e-01  9.38463736e-16 -5.77350269e-01  5.77350269e-01
   8.73792257e-17]
 [-5.00000000e-01  5.00000000e-01  1.12283347e-16  5.00000000e-01
   5.00000000e-01]
 [ 2.88675135e-01 -5.00000000e-01  5.77350269e-01  2.88675135e-01
   5.00000000e-01]]
